In [8]:
import pandas as pd
import os
import glob

In [9]:
od_tenders = pd.read_csv(r'/Users/saurabhlevin/Deployment/flood-data-ecosystem-Odisha/Sources/TENDERS/data/odisha_all_tenders.csv')
od_tenders = od_tenders.loc[od_tenders['Status'] == 'Accepted-AOC']
print(f"Number of accepted tenders: {len(od_tenders)}")
od_tenders

Number of accepted tenders: 13493

,Tender ID,tender_externalreference,tender_title,Work Description,Tender Category,Tender Type,Form of contract,Product Category,Is Multi Currency Allowed For BOQ,Allow Two Stage Bidding,...,Organisation Chain,location,Pincode,No of Bids Received,Tender Value in ₹,Bidder Name,Awarded Value,Status,Contract Date :,Department
2,2020_BPUTW_62754_1,TEQIP-III/2020/OD/bpuo/58,2x1 KW solar PV,laboratory equipment requirement for Research ...,Goods,Open Tender,Item Wise,Laboratory and scientific equipment,No,No,...,Biju Patnaik University of Technology-World Bank,"BIJU PATNAIK UNIVERSITY OF TECHNOLOGY, ODISHA",769015.0,2.0,NaN,EMBESYS TECHNOLOGIES,"3,524,031",Accepted-AOC,22-Jan-2021,Biju Patnaik University of Technology-World Bank
14,2020_OMC_59608_1,NIT-5/OMC/Civil/2020,Environmental related civil works for sub grad...,Environmental related civil works for sub grad...,Works,Open Tender,Percentage,Civil Works - Others,No,No,...,Orissa Mining Corporation,Soth-Kaliapani,755028.0,2.0,"47,81,000",AJIT KUMAR DHIR,"4,064,093.84",Accepted-AOC,01-Jan-2021,Orissa Mining Corporation
23,2018_CERWI_48091_2,Building Tender Online RWCSBP-45,Construction of Odisha Adarsha Vidyalaya (Mode...,Construction of Odisha Adarsha Vidyalaya (Mode...,Works,Open Tender,Percentage,Civil Works - Buildings,No,No,...,CE RW I||RWCIRCLE-SAMBALPUR,Kuchinda,768222.0,2.0,"3,20,00,000",MONALISA ENGICONS,"29,820,912.04",Accepted-AOC,07-Jul-2022,CE RW I||RWCIRCLE-SAMBALPUR
25,2019_CERWI_53180_2,ONLINE-13-2018-19 (BRIDGES),Construction of Bridge over Local nallah on RD...,Construction of Bridge over Local nallah on RD...,Works,Open Tender,Percentage,Civil Works - Bridges,No,No,...,CE RW I||RWCIRCLE-SAMBALPUR,Sambalpur,768001.0,2.0,"3,69,12,816",MONALISA ENGICONS,"32,132,618.52",Accepted-AOC,07-Jul-2022,CE RW I||RWCIRCLE-SAMBALPUR
27,2020_CCEBA_59020_1,EE CKD NCB/05 /ORDRIPW-05 / 2019-20,Transeverse drain,Earth work hume pipe RCC M 20,Works,Open Tender,Item Wise,Civil Works - Others,No,No,...,"CCE Potteru Irr.Project,Balimela",CHITRAKONDA,764052.0,2.0,"66,37,000",M/S UNICORN CONSTRUCTION,"7,276,609",Accepted-AOC,29-Jul-2022,"CCE Potteru Irr.Project,Balimela"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57046,2024_CERWI_100971_9,SE/RW/BDKII/TCN16/2023-24,Construction of Sub Centre Building at Jagula ...,Construction of Sub Centre Building at Jagula ...,Works,Open Tender,Percentage,Civil Works - Buildings,No,No,...,CE RW I||RWCIRCLE-BALASORE||RWDIVISION-BHADRAK-II,Bhadrak,756100.0,1.0,"35,06,000",NIRAKAR MALLICK,"2,975,796",Accepted-AOC,30-Oct-2024,CE RW I||RWCIRCLE-BALASORE||RWDIVISION-BHADRAK-II
57047,2023_DZPBR_85370_1,"IFB-CDO-cum-EO,ZP,BGH,02 of 2022-23",Construction of Sub centre building at Arda of...,Building works(civil),Works,Open Tender,Percentage,Civil Works - Buildings,No,No,...,Panchayati Raj and Drinking Water Department O...,Bijepur,768032.0,1.0,"31,58,750",CHINTAMANI SAHU,"2,685,253.6",Accepted-AOC,01-May-2023,Panchayati Raj and Drinking Water Department O...
57050,2023_DZPBR_85370_2,"IFB-CDO-cum-EO,ZP,BGH,02 of 2022-23",Construction of Sub centre building at Bandhpa...,Building works (civil),Works,Open Tender,Percentage,Civil Works - Buildings,No,No,...,Panchayati Raj and Drinking Water Department O...,Barpali,768029.0,1.0,"31,58,433",MANOJ KUMAR MAHANA,"3,158,433.336",Accepted-AOC,01-May-2023,Panchayati Raj and Drinking Water Department O...
57051,2023_DZPBR_85370_5,"IFB-CDO-cum-EO,ZP,BGH,02 of 2022-23",Construction of Sub centre building at Charpal...,Building works (civil),Works,Open Tender,Percentage,Civil Works - Buildings,No,No,...,Panchayati Raj and Drinking Water Department O...,Bijepur,768032.0,1.0,"31,58,750",CHINTAMANI SAHU,"2,685,253.602",Accepted-AOC,01-May-2023,Panchayati Raj and Drinking Water Department O...
57054,2023_DZPBR_85370_9,"IFB-CDO-cum-EO,ZP,BGH,02 of 2022-23",Construction of Sub centre building at Kandpal...,building works (civil),Works,Open Tender,Percentage,Civil Works - Buildings,No,No,...,Panchayati Raj and Drinking Water Department O...,Ambabhona,768031.0,1.0,"31,58,433",GITANJALI PRADHAN,"3,158,433.36",Accepted-AOC,01-May-2023,Panchayati Raj and Drinking Water Department O...

In [10]:
od_tenders['Awarded Value'].str.replace(',','').astype(float).sum()

np.float64(160425643661.38892)

In [12]:
od_flood_tenders = pd.read_csv(r'/Users/saurabhlevin/Deployment/flood-data-ecosystem-Odisha/Sources/TENDERS/data/flood_tenders_all.csv')
od_flood_tenders = od_flood_tenders.loc[od_flood_tenders['Status'] == 'Accepted-AOC']
print(f"Number of accepted tenders: {len(od_flood_tenders)}")
od_flood_tenders

Number of accepted tenders: 2738

,Tender ID,tender_externalreference,tender_title,Work Description,Tender Category,Tender Type,Form of contract,Product Category,Is Multi Currency Allowed For BOQ,Allow Two Stage Bidding,...,is_flood_tender,positive_keywords_dict,negative_keywords_dict,Season,Scheme,Erosion,Roads_Bridges_Embkt,Response Type,Flood Response - Subhead,month
4,2019_CERWI_53180_2,ONLINE-13-2018-19 (BRIDGES),Construction of Bridge over Local nallah on RD...,Construction of Bridge over Local nallah on RD...,Works,Open Tender,Percentage,Civil Works - Bridges,No,No,...,True,"{'Flood': 0, 'Embankment': 0, 'embkt': 0, 'Rel...","{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Post-Monsoon,NaN,False,True,Repair and Restoration,"{'Construction': 2, 'Bridge': 2}",2022_07
8,2021_CERWI_71552_5,EE/RW/Jls- 07/2021-22,Repair and restoration of Uluda to Aruhabruti ...,Road Works,Works,Open Tender,Percentage,Civil Works - Roads,No,No,...,True,"{'Flood': 0, 'Embankment': 0, 'embkt': 0, 'Rel...","{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Post-Monsoon,NaN,False,True,Repair and Restoration,"{'repair': 1, 'restoration': 1}",2022_07
21,2021_EICCL_74577_1,Bid Identification No.S.E.E.C (RandB) 12/2021-22,Provision of Integrated Life Safety and Automa...,Provision of Integrated Life Safety and Automa...,Works,National Competitive Bid,Percentage,Electrical Works,No,No,...,True,"{'Flood': 0, 'Embankment': 0, 'embkt': 0, 'Rel...","{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Post-Monsoon,NaN,False,False,Preparedness Measures,{'Protection': 2},2022_07
27,2022_CEBBS_79393_1,Bid Identification No.SE-HID-02/2022-23,Engagement of different categories of labour /...,Engagement of different categories of labour /...,Services,Open Tender,Item Rate,Human Resources Supply,No,No,...,True,"{'Flood': 0, 'Embankment': 0, 'embkt': 0, 'Rel...","{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Monsoon,NaN,False,False,Preparedness Measures,{'Period': 1},2022_07
60,2022_CERWI_78672_2,EE/RWELECT/SBP/03/2022-23,Shifting of 11Kv line for work of construction...,Shifting of 11Kv line for work of construction...,Works,Open Tender,Percentage,Electrical Works,No,No,...,True,"{'Flood': 0, 'Embankment': 0, 'embkt': 0, 'Rel...","{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Monsoon,NaN,False,True,Repair and Restoration,{'Construction': 2},2022_07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12443,2024_ORULB_102004_8,JM-09/2023-24,Special repair of drain with cover slab from D...,WORKS,Works,Open Tender,Percentage,Civil Works - Others,No,No,...,True,"{'Flood': 0, 'Embankment': 0, 'embkt': 0, 'Rel...","{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Pre-Monsoon,NaN,False,True,Repair and Restoration,"{'repair': 1, 'Drain': 1}",2024_10
12445,2024_CEMIB_100361_10,SE-MID-PDP- 09/2023-24,Improvement to Amdhara Check Dam near village ...,Improvement to Amdhara Check Dam near village ...,Works,Open Tender,Percentage,Civil Works - Water Works,No,No,...,True,"{'Flood': 0, 'Embankment': 0, 'embkt': 0, 'Rel...","{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Post-Monsoon,NaN,False,False,Repair and Restoration,"{'improvement': 2, 'imp.': 2, 'Check Dam': 4}",2024_10
12446,2024_ORULB_101402_69,EO/RGP/08 of 2023-24,Construction of C.C Drain with cover slab form...,Construction of C.C Drain with cover slab form...,Works,Open Tender,Percentage,Civil Works - Others,No,No,...,True,"{'Flood': 0, 'Embankment': 0, 'embkt': 0, 'Rel...","{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Post-Monsoon,NaN,False,True,Repair and Restoration,"{'Construction': 2, 'Drain': 2}",2024_10
12451,2023_ORULB_98027_1,SNGM-22/2023-24,Construction of Drain and Culvert with Slab fr...,Construction of Drain and Culvert with Slab fr...,Works,Open Tender,Percentage,Civil Works - Others,No,No,...,True,"{'Flood': 0, 'Embankment': 0, 'embkt': 0, 'Rel...","{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Post-Monsoon,NaN,False,True,Repair and Restoration,"{'Construction': 2, 'Drain': 4}",2024_10
12457,2024_ORULB_102004_21,JM-09/2023-24,Special repair of Culvert for Bhanja Hutting R...,WORKS,Works,Open Tender,Percentage,Civil Works - Others,No,No,...,True,"{'Flood': 0, 'Embankment': 0, 'embkt': 0, 'Rel...","{'Floodlight': 0, 'Flood Light': 0, 'GAS': 0, ...",Pre-Monsoon,NaN,False,True,Repair and Restoration,{'repair': 1},2024_10

In [13]:
od_flood_tenders['Awarded Value'].str.replace(',','').astype(float).sum()

np.float64(55378594974.02461)